### ISSUE TITLE
🤔 [CH01]Q1 운영체제의 정의를 설명하고 그 기능에 대해 아는대로 말해주세요.

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#18]

**Comment by dianestar** [comment]
운영체제란 하드웨어 바로 윗단에 위치한 소프트웨어로 하드웨어를 사용자 및 다른 소프트웨어들과 연결해주는 역할을 수행합니다. 하드웨어 쪽 인터페이스로서는 한정된 컴퓨터의 자원을 효율적이고 형평적으로 관리하기 위한 자원 관리자 역할을 하며, 사용자 쪽 인터페이스로서는 사용자로 하여금 하드웨어의 복잡성을 전부 알고 있지 않아도 컴퓨터를 편리하게 사용할 수 있도록 환경을 제공하는 역할을 합니다. 더불어, 운영체제 자신 및 컴퓨터 시스템을 보호하는 기능 또한 담당합니다.

**Comment by codenamehee** [comment]
운영체제는 컴퓨터 하드웨어 바로 위에 설치되어 사용자 및 다른 소프트웨어와 하드웨어를 연결하는 소프트웨어 계층입니다.
운영체제는 사용자가 컴퓨터 시스템을 편리하게 사용할 수 있는 환경을 제공하고, 컴퓨터 시스템 자원을 효율적으로 사용할 수 있도록 관리합니다.

**Comment by gzgzg2** [comment]
운영체제는 컴퓨터 하드웨어 바로 위에 설치되어 사용자 및 다른 소프트웨어와 하드웨어를 연결하는 소프트웨어 계층이다. 운영체제는 사용자가 컴퓨터를 쉽게 다룰 수 있게 GUI 인터페이스 제공하고, 하드웨어 자원을 효율적으로 사용할 수 있게 도와준다.
