### ISSUE TITLE
🤔 [CH01]Q2 운영체제 운용 기법 중 시분할 시스템에 대하여 설명해주세요.

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#19]

**Comment by dianestar** [comment]
시분할 시스템이란 오늘날 범용적인 컴퓨터에 가장 많이 활용되는 운용 기법으로, 여러 작업이 사용하고자 할 때에 아주 작은 시간 단위로 나누어 한정된 자원을 나눠쓸 수 있도록 하는 방식으로, 고전적 운용 기법인 일괄처리방식에 비해 짧은 응답 시간을 갖기에 사용자와의 상호작용성이 높아진다는 장점이 있습니다.

**Comment by codenamehee** [comment]
현대의 운영체제 처리 방식으로, 여러 작업을 수행할 때 컴퓨터의 처리 능력을 일정한 시간 단위로 분할하여 사용하는 것입니다. 
컴퓨터가 사용자들의 프로그램을 번갈아가며 처리해줌으로써 각 사용자에게 독립된 컴퓨터를 사용하는 느낌을 주게 됩니다.

**Comment by gzgzg2** [comment]
시분할 시스템은 여러 작업을 수행할 때 CPU를 일정한 시간 단위로 프로그램에게 할당하여 처리해줌으로써 각 사용자에게 독립된 컴퓨터를 사용하는 느낌을 준다. 라운드 로빈(Round Robin)방식이라고도 한다. 하나의 CPU는 같은 시점에서 여러 개의 작업을 동시에 수행할 수 없기 때문에, CPU의 전체 사용시간을 작은 작업 시간량으로 쪼개어 그 시간량 동안만 번갈아가면서 CPU를 할당하여 각 작업을 처리하는 방법이다. 모든 작업이 동시에 진행되는 것처럼 대화식 처리가 가능하다. 각 작업에 대한 응답시간을 최소화 하는 것이 목적이다.
