### ISSUE TITLE
🤔 [CH01]Q3 운영체제의 개념을 좁은 의미와 넓은 의미로 나누어 간략하게 설명하시오.

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#20]

**Comment by codenamehee** [comment]
좁은 의미의 운영체제는 커널을 의미합니다. 커널은 운영 체제의 핵심 부분으로 메모리에 상주하는 일부분을 이야기합니다. 반면 넓은 의미의 운영체제는 커널과 각종 주변 시스템 유틸리티를 포함한 개념입니다.

**Comment by dianestar** [comment]
좁은 의미의 운영체제는 항상 메모리에 상주하는 '커널'을 의미하며, 넓은 의미의 운영체제는 커널 이외에도 각종 주변 시스템 유틸리티까지 포함합니다.

**Comment by gzgzg2** [comment]
운영체제의 좁은 의미는 운영체제 커널을 의미하고 커널은 운영체제의 핵심 부분임으로 전원이 켜짐과 동시에 메모리에 상주합니다. 운영체제의 넓은 의미는 운영체제의 커널과 각종 주변 유틸리티 시스템을 포함한 개념입니다.
