### ISSUE TITLE
🤔 [CH02]Q1 사용자 프로그램이 I/O를 요청했을 때 일어나는 일을 설명해보시오.

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#21]

**Comment by dianestar** [comment]
I/O 작업은 보안 상 문제가 될 수 있는 작업이므로 운영체제만 수행 가능합니다. 따라서, 사용자 프로그램이 I/O 작업을 하고자 할 때에는 시스템콜을 통해 CPU에게 소프트웨어 인터럽트를 발생시키게 됩니다. 인터럽트를 발견한 CPU는 제어권을 운영체제에게 넘겨주며, 운영체제는 디바이스 컨트롤러에게 I/O 작업을 수행할 것을 명령합니다. I/O 작업이 끝나면 이번에는 디바이스 컨트롤러가 CPU에게 I/O 작업이 완료되었음을 알리기 위해 하드웨어 인터럽트를 발생시키며, 인터럽트를 발견한 CPU는 해당 디바이스의 로컬 버퍼에 저장된 데이터를 메인 메모리로 전달해오고 운영체제는 이전에 I/O 작업을 요청한 프로그램을 다시 CPU를 할당받을 수 있는 상태로 전환시킵니다.

**Comment by codenamehee** [comment]
먼저, CPU가 운영체제에게 I/O 요청 보낸다. 그 즉시 CPU의 제어권이 운영체제로 넘어가게 되고 CPU는 지금까지 하던 일을 멈추고 프로그램의 현재 상태를 저장한 후, 인터럽트에 의해 처리해야 할 커널의 루틴으로 이동한다. 루틴에 따라 입출력 장치의 컨트롤러에게 연산을 요청하고, 컨트롤러는 로컬버퍼로 해당 데이터를 읽어온다. 컨트롤러가 데이터를 읽어오는 동안 운영체제는 CPU를 프로그램 B에 할당하여 CPU가 프로그램 B의 작업을 처리하도록 한다. 이후 입출력 컨트롤러부터 CPU로 데이터 입출력 작업이 완료되었다는 인터럽트가 전달되면 CPU는 B에 대한 수행 정보를 저장하고 인터럽트를 처리하게 된다.

**Comment by gzgzg2** [comment]
사용자는 직접 입출력 장치에 접근할 수 없기 때문에 시스템 콜을 하여 운영체제에게 I/O 작업을 요청한다. 운영체제는 요청받은 I/O 명령을 사용자 프로그램 모드가 아닌 커널 모드에서 해당 요청에 맞는 처리코드를 수행하게 된다. 예를 들어 디스크에서 자료를 읽어오는 시스템 콜이라면, CPU가 디스크 컨트롤러에게 데이터를 읽어오라는 명령을 내린다.
