### ISSUE TITLE
🤔 [CH02]Q2 DMA 컨트롤러의 기능을 설명해주세요.

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#22]

**Comment by dianestar** [comment]
DMA 컨트롤러는 CPU 외에 직접 메모리에 접근할 수 있는 컨트롤러입니다. 원칙적으로 메인 메모리에는 CPU만 접근이 가능하지만, 빈번한 I/O 작업이 인터럽트를 걸 경우 CPU의 작업이 방해받는 문제가 발생합니다. 따라서, 해당 문제를 해결하고 CPU의 효율성을 높이기 위해 DMA 컨트롤러는 I/O 작업이 완료되면 해당 I/O 디바이스의 로컬 버퍼에 저장된 값을 메인 메모리로 옮겨와 주는 역할을 대행하고 여러 I/O 작업 완료 인터럽트를 모아 CPU에게 한 번만 인터럽트를 발생시킵니다.

**Comment by codenamehee** [comment]
일종의 컨트롤러로서, CPU가 입출력 장치들이 수시로 발생시키는 인터럽트로 인해 사용상의 효율이 떨어지는 것을 막아주고자 CPU대신 로컬버퍼에서 메모리로 입출력 관련 데이터를 읽어오는 작업을 대신 처리한다.

**Comment by gzgzg2** [comment]
CPU가 입출력 장치들의 메모리 접근 요청에 의해 자주 인터럽트 당하는 것을 막아주어서 CPU에 발생하는 인터럽트의 빈도를 줄여 CPU를 효율적으로 관리할 수 있게 도와주는 역할을 한다. DMA를 사용하면 CPU가 로컬버퍼에서 메모리로 읽어오는 작업을 DMA가 대행한다. DMA는 바이트 단위가 아니라 블록이라는 큰 단위로 정보를 메모리로 읽어온 후에 CPU에게 인터럽트를 발생시켜 작업이 끝난 것을 알린다.
