### ISSUE TITLE
🤔 [CH02]Q2 시스템콜에 대해 설명해보세요.

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#23]

**Comment by dianestar** [comment]
시스템콜이란 입출력, 메모리 접근과 같이 보안 상의 문제로 인해 운영체제만 수행할 수 있는 서비스를 이용하기 위해 사용자 프로그램이 커널 공간에 있는 함수를 호출하는 인터페이스를 말합니다.

**Comment by codenamehee** [comment]
시스템콜이란 프로그램이 입출력 작업을 수행하기 위해 운영체제의 함수를 호출하는 것이다.

**Comment by gzgzg2** [comment]
시스템 콜이란 사용자 프로그램이 특권명령을 수행하기 위해 운영체제에게 해당 작업을 요청하는 행위이다. 시스템 콜은 일종의 소프트웨어적인 인터럽스로서 사용자 프로그램이 시스템 콜을 할 경우 트랩이 발생해 CPU의 제어권이 운영체제로 넘어가게 된다. 그러면 운영체제는 해당 시스템 콜을 처리하기 위한 루틴으로 가서 정의된 명령을 수행한다.
