### ISSUE TITLE
🤔 [CH03]Q1 프로세스 문맥교환이 어떠한 상황에서 발생하는지 설명해주세요.

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#24]

**Comment by dianestar** [comment]
문맥교환이란 타이머 인터럽트가 발생한 경우 또는 I/O 작업 요청 등이 발생한 경우 CPU의 제어권이 실행 중이던 프로세스에서 다른 프로세스로 이양되는 과정으로, 현재 수행 중이던 프로세스의 문맥을 PCB에 저장하고 다음 실행할 프로세스의 문맥을 PCB에서 가져오는 것입니다.

**Comment by codenamehee** [comment]
프로세스 문맥교환은 CPU를 점유하는 프로세스가 A에서 B로 바뀔 때 발생한다. 이러한 상황의 예시로는 타이머 인터럽트가 발생했을 경우와 실행 중이던 프로세스가 입출력 요청에 의해 봉쇄 상태로 바뀌어 대기 중이던 프로세스가 CPU를 점유하게 되었을 경우 등이 있다.

**Comment by gzgzg2** [comment]
프로세스 문맥교환은 타이머 인터럽트가 발생하거나 I/O System call이 발생할 때 이뤄진다. system call이나 인터럽트로 단순히 사용자모드에서 커널모드로 변경되는 것은 문맥교환이라고 할 수 없다. 커널모드에서 사용자 모드로의 전환도 일부 문맥은 저장되지만 문맥교환처럼 프로세스를 스위칭 하는 작업보다 오버헤드가 적다.
