### ISSUE TITLE
🤔 [CH03]Q2 적은 양의 메모리를 많은 프로세스에게 할당할 때 발생하는 문제점과 이를 해결하기 위해 개발된 스케줄러를 하나만 선택하여 설명해주세요.

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#25]

**Comment by dianestar** [comment]
프로세스 당 보유하고 있는 메모리의 양이적어지게 되면, 당장 실행해야하는 프로세스의 주소 공간을 메모리에 올려둘 수 없을 정도로 메모리가 부족해질 수 있으며, 해당 경우에는 디스크 입출력이 빈번해지며 성능이 저하되는 문제가 발생합니다. 이와 같은 문제를 해결하기 위해 swapper라고도 불리는 중기 스케줄러는 봉쇄 상태 등 CPU를 할당받을 수 없는 프로세스로부터 메모리를 빼앗아 그 내용을 디스크로 swap-out 하며 메모리에 적재된 프로세스의 수를 동적으로 조절하고 여유 공간을 확보합니다.

**Comment by codenamehee** [comment]
좁은 의미의 운영체제는 커널을 의미합니다. 커널은 운영 체제의 핵심 부분으로 메모리에 상주하는 일부분을 이야기합니다. 반면 넓은 의미의 운영체제는 커널과 각종 주변 시스템 유틸리티를 포함한 개념입니다.

**Comment by codenamehee** [comment]
적은 양의 메모리를 많은 프로세스에게 할당할 때, 메모리에 프로세스의 주소 공간조차 올리지 못하는 경우가 발생하게 되고 시스템의 전체적인 성능이 저하된다. 따라서 이러한 문제점을 해결하기 위해 메모리를 차지하는 프로세서들의 수를 동적으로 제어하는 중기 스케쥴러가 개발되었다. 이 스케쥴러는 봉쇄 상태의 프로세스들과 준비 상태의 프로세스들을 차례로 디스크의 스왑 공간에 스왑 아웃 처리하여 메모리에 적정 수의 프로세스들이 올라와 있을 수 있도록 한다.

**Comment by gzgzg2** [comment]
적은 양의 메모리를 많은 프로세스에게 할당하면 Disk I/O 발생 확률이 높아지기 때문에 성능이 저하되는 문제가 발생할 수 있습니다. 이러한 문제를 해결하기위한 여러 스케줄링 기법이 있는데 그 중에서 현 대에서 가장 유용하게 사용되고 있는 중기 스케줄러에 대해 설명하겠습니다. 중기 스케줄러는 타이머 인터럽트가 발생한 프로세스나 봉쇄상태의 프로세스를 메모리에서 쫓아내고 suspend 상태로 변경합니다. 이때 우선순위는 봉쇄상태의 프로세스가 먼저 쫓겨나고, 봉쇄상태의 프로세스를 쫓아내도 메모리가 부족한 경우에 타이머 인터럽트가 발생한 프로세스를 추가적으로 쫓아냅니다.
