### ISSUE TITLE
🤔 [CH03]Q3 프로세스 제어블록이란 무엇인지 설명하고 프로세스 제어블록의 요소들에 대해 아는대로 설명해주세요.

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#26]

**Comment by gzgzg2** [comment]
ㅁㄴㅁㅇㄴ

**Comment by dianestar** [comment]
Process Control Block 이란 커널에서 각 프로세스를 관리하기 위해 필요한 정보를 갖고 있는 자료구조로, 운영체제의 프로세스 관리 상 필요한 정보인 PID, 프로세스 상태, 스케줄링 우선순위 등, CPU 운영 상 필요한 정보인 Program Counter, Registers 등, 그리고 메모리 및 파일과 같은 자원 관련 stack/data/code의 위치 정보, open file descriptors 등을 포함합니다.

**Comment by codenamehee** [comment]
프로세스 제어블록 즉, PCB란 운영체제가 프로세스들을 관리하기 위해 각 프로세스들에 대한 정보들을 담고 있는 커널 내의 자료구조이다. 제어블록의 요소에는 포인터, 프로세스의 상태, CPU 레지스터의 값, CPU의 스케쥴링 정보, 프로그램 카운터의 값, 메모리 관리 정보 등이 있다.

**Comment by gzgzg2** [comment]
프로세스 제어블록이란 PCB로도 불리고, 프로세스 스왑이 발생했을 때 프로세스의 문맥을 저장하는 역할을 담당합니다. 프로세스 제어블록은 PC(프로그램 카운터), Data의 Stack 위치정보, 프로세스 아이디, 프로세스 상태로 구성되어 있습니다. 프로그램 카운터는 해당 프로세스가 마지막으로 실행했던 영역을 저장하고 있고, Data, Stack의 위치정보는 프로그램 코드에 관련된 정보의 위치가 저장되어 있습니다.
