### ISSUE TITLE
🤔 [CH03]Q4 Q10. 4가지의 프로세스 상태에 대해 각각 설명해주세요.

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#27]

**Comment by dianestar** [comment]
Ready는 실행을 위한 다른 모든 준비가 완료되고 CPU 할당만을 기다리는 상태이며, Running은 CPU가 할당되어 instructions가 수행 중인 상태, Blocked는 입출력 작업 등과 같이 많은 시간을 필요로 하는 이벤트 발생으로 인해 CPU를 할당 받더라도 당장 insturctions 수행이 불가능한 상태, Suspended는 사용자의 일시중지 또는 중기 스케줄러의 swap-out 등 사유로 인해 외부적인 사유로 인해 프로세스의 수행이 중지된 상태 입니다.

**Comment by codenamehee** [comment]
좁은 의미의 운영체제는 커널을 의미합니다. 커널은 운영 체제의 핵심 부분으로 메모리에 상주하는 일부분을 이야기합니다. 반면 넓은 의미의 운영체제는 커널과 각종 주변 시스템 유틸리티를 포함한 개념입니다.

**Comment by codenamehee** [comment]
프로세스 상태는 준비, 실행, 중지, 봉쇄 4가지로 구분할 수 있다. 준비는 CPU를 당장 사용해도 될 준비가 된 상태에서 CPU를 할당받기 위해 기다리는 상태이고 실행은 CPU를 점유하여 명령을 실행중인 상태이다. 중지는 외부 요인에 의해 CPU를 사용하지 못하게 된 상태이고, 봉쇄는 입출력 시스템 콜을 발생시키는 등 CPU를 할당받더라도 당장 명령을 수행할 수 없는 상태를 말한다.

**Comment by gzgzg2** [comment]
프로세스는 Running, Ready, Block, Terminated, Suspended 상태가 있습니다. 이중에서 Ready, Block, Terminated, Suspended 상태에 대해 설명하자면, Ready 상태는 프로세스가 CPU를 할당받았을 때 당장 실행할 준비가 되어있는 상태입니다. Block 상태는 프로세스가 요청한 Event가 수행될 때까지 대기 중인 상태를 의미합니다. Terminated 상태는 프로세스 실행이 종료되었지만 아직 메모리에 저장되어있는 데이터가 회수가 되어있지 않은 상태입니다. Suspended 상태는 프로세스가 외부요인에 의해 종료된 상태를 의미 합니다.
