### ISSUE TITLE
🤔 [CH03]Q5 프로세스와 스레드 각각의 개념을 설명하고, 멀티프로세스보다 멀티스레드가 효율적인 이유를 말씀해주세요.

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#28]

**Comment by codenamehee** [comment]
프로세스는 CPU에서 실행중인 프로그램을 의미하고 스레드는 한 프로세스 내에서 CPU 사용 단위가 여러 개인 경우를 의미한다. 여러 개의 스레드는 한 프로세스 내에서 data, code, OS의 자원과 같은 영역들을 공유하되 CPU사용과 관련된 정보들를 별도로 갖는다. 반면 멀티 프로세스 하에서 프로세스들은 각각의 프로세스들이 별도로 자원 및 CPU를 사용하기 때문에 성능 향상 및 경제성 측면에서 멀티 스레드가 더욱 효율적이다.

**Comment by dianestar** [comment]
프로세스는 실행 중인 프로그램, 즉 운영체제로부터 시스템 자원을 할당받는 단위이며, 스레드는 한 프로세스의 할당 받은 자원 내에서 CPU 수행이 실행되는 흐름의 단위 입니다. 프로세스는 만들 때마다 자료구조를 별도로 생성해야 하므로 메모리가 낭비되고, 프로세스를 생성하거나 프로세스 문맥교환을 수행할 때마다 오버헤드가 큰 반면, 스레드는 code/data 영역 및 운영체제의 자원과 같이 공유할 수 있는 자원들을 최대한 공유하기 때문에 보다 효율적이고 경제적입니다.

**Comment by gzgzg2** [comment]
실행중인 프로그램을 의미하고 스레드는 한 프로세스의 경량 프로세스라고 소개할 수 있습니다. 멀티 프로세스의 경우 프로세스마다 같은 정보를 가지고 있다고 해도 새로운 메모리 영역을 할당받는 반면에 멀티 스레드는 프로그램 실행에 필요한 최소한의 정보만을 새롭게 할당받고 나머지 정보는 프로세스의 메모리를 공유하여 사용할 수 있기 때문에 메모리를 효율적으로 관리하는 측면에서 멀티 프로세스보다 멀티 스레드가 유용합니다.
