### ISSUE TITLE
🤔 [CH03]Q6 스레드의 장점을 아는 대로 전부 말씀해주세요.

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#29]

**Comment by dianestar** [comment]
스레드는 첫째, 빠른 응답성을 가집니다. 한 프로세스 내에서 특정 스레드가 blocked 상태여도 다른 스레드는 CPU를 할당받아 수행할 수 있습니다. 둘째, 자원을 공유합니다. PC, registers, stack 이외의 공유 가능한 자원들을 공유하여 자원을 절약합니다. 셋째, 프로세스를 여러 개 만드는 것에 비해 경제적입니다. 멀티프로세스는 생성 및 문맥교환 과정에서 많은 오버헤드를 동반하지만, 스레드는 최대한 많은 자원과 문맥을 공유하여 보다 낮은 처리 비용으로 높은 성능과 처리량을 제공합니다. 마지막으로, 높은 병렬성 또한 가지고 있습니다.

**Comment by codenamehee** [comment]
스레드는 한 프로세스 내에서 CPU를 다양하게 활용할 수 있기 때문에 응답이 빠르고, 스레드끼리 코드/데이터/OS자원과 같은 자원들을 공유함으로써 자원 절약 및 성능 향상에 효과적이며 경제적이라는 장점이 있다. 더불어 멀티프로세스 환경 하에서 스레드는 병렬성이 높아져 작업 처리를 훨씬 빨리 할 수 있게 된다.

**Comment by gzgzg2** [comment]
멀티 스레드 웹 프로그래밍 환경을 예로 들면, 웹 홈페이지에 접속할 때 데이터를 가져오는 스레드, 화면을 표시하는 작업을 진행하는 스레드가 여럿 있으면 하나의 작업을 수행될 때까지 기다리지 않고 다른 스레드에서 나머지 작업을 진행할 수 있기 때문에 응답속도가 증가한다는 장점이 있습니다.
