### ISSUE TITLE
🤔 [CH04]Q1 프로세스 생성 과정에 대해 설명해주세요. 

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#42]

**Comment by codenamehee** [comment]
프로세스는 복제를 통해 생성됩니다. 먼저 부모 프로세스가 fork()라는 시스템 콜을 발생시키면 CPU의 제어권이 커널로 넘어가고 커널이 부모 프로세스의 주소 공간, 프로세스 카운터, 프로세스 제어 블록, 커널 스택 등 모든 문맥을 복사한 자식 프로세스를 생성합니다. 이후 자식 프로세스가 exec()이라는 시스템 콜을 통해 완전히 새로운 프로그램을 덮어쓰게 되고 해당 프로그램의 명령어를 수행하게 되면서 새로운 프로세스가 됩니다.

**Comment by dianestar** [comment]
운영체제가 부팅되면 운영체제는 최조의 init 프로세스를 생성하고, 그 후에 생성되는 모든 사용자 프로세스는 fork 라는 시스템콜을 통해 부모 프로세스를 복제하여 자식 프로세스를 생성하는 방식으로 만들어집니다. 생성된 자식 프로세스는 exec 시스템콜을 통해 새로운 프로그램을 메모리에 덮어 씌운 후 해당 프로그램을 실행합니다.

**Comment by gzgzg2** [comment]
최초의 프로세스를 생성하고 이후 생성되면 fork() 시스템콜을 통해 루트 프로세스를 복제하여 생성한다. 복제된 프로세스는 새로운 메모리 공간에 부모 프로세스와 동일한 정보를 갖게된다. exec() 시스템콜을 호출하면 새로운 프로그램으로 주소 공간을 덮어씌운다. 새로운 프로그램으로 덮어씌우면 루트 프로세스와 문맥이 달라지므로 루트 프로세스의 실행시점부터 수행하지 않고 처음부터 실행하게 된다.
