### ISSUE TITLE
🤔 [CH04]Q3 IPC 메커니즘 중 간접적으로 메세지를 전달하는 방식은 어떠한 메세징 기법인지 대답해주세요.

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#44]

**Comment by codenamehee** [comment]
IPC 메커니즘에는 메시지 전달 방식과 공유메모리 방식 두가지가 있습니다. 그 중, 간접적으로 메시지를 전달하는 방식은 메시지 전달 방식 중 간접 통신에 해당합니다. 이 경우 프로세스들이 통신을 할 때, 서로 공유하고 있는 메일박스나 포트를 통해 메시지를 주고 받으며 통신합니다.

**Comment by dianestar** [comment]
IPC의 기법 중 Message Passing 기법에는 direct/indrect 방식이 있는데, 이 중 간접적으로 메시지를 전달하는 방식인 indirect 방식은 통신하려는 프로세스의 이름을 명시적으로 표시하지 않고, mailbox나 port를 통해 간접적으로 전달합니다. 해당 mailbox나 port를 공유하는 프로세스 간의 통신이 가능합니다.

**Comment by gzgzg2** [comment]
Indirect Communication 기법 입니다. Indirect Communication은 직접적으로 메세지를 전달하지 않고, port나 mailbox를 통해 메세지를 주고받습니다.
