### ISSUE TITLE
🤔 [CH04]Q4 프로세스와 관련된 시스템 콜 명령어 중 두 개를 골라 설명해주세요.

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#45]

**Comment by codenamehee** [comment]
fork()와 exec()이라는 시스템 콜이 있습니다. fork()는 부모 프로세스가 자식 프로세스를 생성하고자 할 때 커널에게 보내는 시스템 콜로, 부모 프로세스와 완전히 동일한 자식 프로세스가 복제되어 생성됩니다. 이후 자식 프로세스가 exec() 시스템 콜을 통해 새로운 프로그램을 덮어쓰게 되고 이를 통해 부모 프로세스와는 완전히 다른 프로세스가 됩니다.
