### ISSUE TITLE
🤔 [CH05]Q1 Dispatcher의 역할은 무엇인가요?

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#46]

**Comment by dianestar** [comment]
Dispatcher란 CPU 스케줄러에 의해 선택된 프로세스에게 실제로 Context Switching을 통해 CPU 제어권을 넘겨주는 역할을 합니다.

**Comment by codenamehee** [comment]
운영체제 안에 있는 코드로 CPU의 제어권을 CPU Scheduler에 의해 선택된 프로세스에게 넘겨주는 역할을 합니다.
