### ISSUE TITLE
🤔 [CH05]Q2 Starvation(기아 상태)란 무엇인지 설명해주세요.

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#47]

**Comment by dianestar** [comment]
Starvation이란 특정 프로세스가 CPU를 할당받지 못하고 계속해서 무한정 기다리는 상황을 의미합니다.

**Comment by codenamehee** [comment]
기아 상태란 특정 프로세스가 CPU의 제어권을 넘겨 받지 못하고 계속해서 기다리게 되는 상태를 의미합니다.

**Comment by gzgzg2** [comment]
기아상태란 특정 프로세스가 자원 & CPU를 넘겨받지 못하고 무한히 기다리게 되는 상태를 의미합니다.
