### ISSUE TITLE
🤔 [CH05]Q3 선점형(Preemptive) 스케줄링과 비선점형(Non-preemptive) 스케줄링의 차이점을 설명하고 각각의 예시(FCFS, SJF 등의 스케줄링 알고리즘 중 선택)를 하나씩 들어주세요.

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#48]

**Comment by dianestar** [comment]
선점형 스케줄링은 특정 프로세스가 CPU를 차지하고 있고 해당 프로세스의 CPU 작업이 끝나지 않았더라도 다른 프로세스가 CPU 제어권을 강제로 빼앗을 수 있는 스케줄링이며, 그 예시로는 일정 할당 시간이 지나면 타이머 인터럽트를 통해 프로세스의 작업이 끝나지 않았더라도 프로세스에게서 CPU 제어권을 빼앗아 다른 프로세스에게 넘겨주는 Round Robin 스케줄링을 들 수 있습니다. 비선점형 스케줄링은 특정 프로세스가 CPU를 차지하고 있다면 해당 프로세스가 작업을 끝내고 CPU를 자진으로 반납할 때까지 다른 프로세스가 CPU를 할당받을 수 없는 스케줄링으로, 예시로는 ready queue에 도착한 순서대로 CPU를 할당 받고 사용하는 FCFS 스케줄링이 있습니다.

**Comment by gzgzg2** [comment]
선점형 스케줄링은 먼저 도착한 프로세스가 아직 CPU에서 실행 중 이어도 다른 프로세스가 CPU를 강제로 빼앗을 수 있는 스케줄링을 의미합니다. 비선점형 스케줄링은 최초로 도착한 프로세스의 작업이 끝나 스스로 CPU를 반납할 때까지 다른 프로세스에게 CPU를 빼앗기지 않는 스케줄링 입니다.

**Comment by codenamehee** [comment]
선점형 스케쥴링은 특정 프로세스로부터 CPU의 제어권을 강제로 빼앗아 다른 프로세스에게 이를 넘기는 스케쥴링 방식이고, 비선점형 스케쥴링은 특정 프로세스가 CPU를 사용하고 있는 상황에서 이를 강제로 빼앗지 않고 해당 프로세스의 작업이 완료되어 CPU를 자진으로 반납할 때까지 기다리는 스케쥴링 방식입니다. 선점형 스케쥴링 알고리즘에는 프로세스 별로 CPU의 할당 시간이 지나면 다른 프로세스에게 CPU의 제어권을 넘겨주는 라운드 로빈 알고리즘이 있고, 비선점형 스케쥴링 알고리즘에는 CPU의 ready queue에서 가장 빠른 순서의 프로세스에게 CPU의 제어권을 넘겨주는 FCFS 알고리즘이 있습니다.
