### ISSUE TITLE
🤔 [CH05]Q4 Multilevel Queue와 Multilevel Feedback Queue를 비교하여 설명해주세요.

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#49]

**Comment by dianestar** [comment]
Multilevel Queue란 ready queue를 여러 개로 분할하여 관리하는 스케줄링으로, 분할된 큐마다 다른 스케줄링 알고리즘을 활용할 수 있으며, 큐 자체에 대한 스케줄링 알고리즘 또한 필요하다는 특징을 갖습니다. Multilevel Feedback Queue는 Multilevel Queue와 유사하게 ready queue를 여러 개로 분할하여 관리하는 것 분만 아니라 프로세스들이 큐 간에 이동할 수 있다는 특징이 있습니다. Multilevel Queue는 우선순위가 높은 큐에 프로세스가 남아있다면 우선순위가 낮은 큐에 들어있는 프로세스들은 starvation을 겪게되는 문제가 있는데, Multilevel Feedback Queue는 큐 간의 이동이 가능한 특징 및 Aging 기법을 활용하여 해당 문제점을 보완할 수 있습니다.

**Comment by gzgzg2** [comment]
Multilevel Queue란 Ready Queue를 우선순위 별로 분리하여 관리하는 스케줄링 기법을 말한다. 각 큐는 독립적인 알고리즘을 가질 수 있으며 우선순위가 높은 Ready Queue의 프로세스를 CPU에 먼저 할당한다. 하지만 이러한 스케줄링 기법은 기아현상이 나타날 수 있으므로 각 Queue의 CPU time을 적절한 비율로 할당해야 한다.

Multilevel Feedback Queue는 Aging 기법이 적용되어있는 Queue이다. Multilevel Queue 와 다르게 프로세스가 다른 큐로 이동할 수 있다. Multilevel Feedback Queue의 Ready Queue는 각 큐마다 CPU 버스트 시간이 다르게 설정되어 있는데, 첫번째로 실행되는 큐에서 실행을 끝내지못하면 두번째 큐로 넘어가는 형식의 알고리즘이 적용되어 있다. 두번째 큐에서도 실행을 끝내지못하면 FSFS가 적용된 세번째 큐로 이동하게 된다.

**Comment by codenamehee** [comment]
멀티레벨 큐는 준비 큐를 여러개로 분할하여 관리하는 스케쥴링 기법이다. 각 큐들은 우선순위에 차이가 있고 사용자와의 상호작용에 필요한 프로세스들을 처리하는 foreground queue가 계산 위주의 프로세스들이 대기하는 background queue에 비해 높은 우선순위를 갖는다. CPU는 우선순위가 높은 큐들의 프로세스들에게 우선적으로 할당되며 각 큐는 독립적인 스케쥴링 기법을 통해 내부의 프로세스들을 스케쥴링한다. 
 멀티레벨 피드백 큐는 준비 큐를 여러개로 분할하여 관리한다는 점에서 멀티레벨 큐와 유사하지만 프로세스들이 다른 큐로 이동이 가능하다는 점에서 차이가 있다. 예를 들어 에이징 기법의 경우 우선순위가 낮은 큐에서 오래 기다린 프로세스들을 우선순위가 높은 큐로 이동시켜 CPU를 할당받을 수 있도록 한다. 이와 같은 특징은 멀티레벨 큐에서 발생할 수 있는 기아 현상을 예방함으로써 CPU를 보다 효율적으로 사용할 수 있도록 한다.
