### ISSUE TITLE
🤔 [CH06]Q2 Mutex와 Semaphore의 차이점을 설명해주세요.

### ISSUE THREAD

**Issue by dianestar** [CS-Oh-Yeahs/os_study#51]

**Comment by gzgzg2** [comment]
Mutex는 Locking 매커니즘으로 자원의 개수가 하나일 때 적용하는 프로세스 동기화 객체이다. 오직 하나의 쓰레드만이 동일한  시점에 Mutex를 얻어 임계구역에 들어오고 나갈 때 자원을 해제할 수 있다. 
Semaphores는 공유자원이 여러개일 경우 사용하며 block/wakeup 알고리즘이 적용된 객체이다.

앞서 말한 것처럼 세마포어는 뮤텍스와 다르게 공유자원이 여러개일 때 사용되며 자원을 해제하는 대상는 자원을 가지고 있는 모든 프로세스가 될 수 있다.

**Comment by codenamehee** [comment]
뮤텍스와 세마포어는 모두 프로세스의 동기화 기법이라는 점에서 동일하지만 뮤텍스는 오직 1개의 프로세스 또는 쓰레드만이 접근할 수 있고, 세마포어는 세마포어의 변수만큼의 프로세스 혹은 쓰레드가 접근할 수 있다는 점에서 차이가 있습니다. 또한 세마포어는 현재 수행중인 프로세스가 아닌 다른 프로세스도 세마포어를 해제하고 잠글 수 있지만 뮤텍스는 락을 획득한 프로세스만이 그 락을 해제할 수 있습니다.
