### ISSUE TITLE
🤔 [CH06]Q3 Critical Section(임계구역)에 대한 요구사항 세 가지에 대해 설명해주세요.

### ISSUE THREAD

**Issue by dianestar** [CS-Oh-Yeahs/os_study#52]

**Comment by dianestar** [comment]
첫째, Mutual Exclusion은 하나의 프로세스가 Critical Section에 들어가 있을 경우 해당 프로세스 이외의 모든 다른 프로세스들은 Critical Section에 진입할 수 없다는 상호 배제의 원리이고, 둘째, Progress는 어떠한 프로세스도 Critical Section에 들어가 있지 않을 때 Critical Section에 진입하기를 원하는 프로세스가 있을 경우 해당 프로세스가 Critical Section에 진입할 수 있도록 허용해주어야 한다는 진행의 원리이며, 마지막으로, Bounded Waiting은 특정 프로세스가 Critical Section에 진입하기를 요청한 시점부터 요청이 수락될 때까지의 시점까지 Critical Section에 진입하는 다른 프로세스들의 개수를 제한하여 프로세스가 대기하는 시간이 유한할 수 있도록 해야한다는 원리입니다.

**Comment by gzgzg2** [comment]
요구사항 세가지로는 Mutual Exclustion, Progress, Bounded Waiting이 있습니다.
Mutual Exclustion은 어떤 프로세스가 임계구역에서 수행 중이면 다른 프로세스들은  임계구역에 접근하지 않아야 한다는 것입니다.
Progress는 임계구역에 접근한 프로세스가 하나도 없는 상황에서 다른 프로세스가 임계구역에 접근하길 원하면 접근을 허용해야한다는 것이고
Bounded Waiting은 기아현상을 방지하기 위해 프로세스가 임계구역에 들어가려고 요청한 후부터 그 요청이 허용될 때까지 다른 프로세스가 임계구역에 접근하는 횟수에 한계가 있어야 한다는 것 입니다.

**Comment by codenamehee** [comment]
임계구역에 대한 요구사항 세가지에는 Mutual Exclusion, Progress, Bounded Waiting 세 가지가 있습니다. 먼저, Mutual Exclusion은 어떤 프로세스가 임계 구역 부분을 수행중이면 다른 프로세스는 그들의 임계 구역을 수행할 수 없다는 상호 배제의 원리이고, 두번째 Progress는 아무도 임계 구역에 있지 않은 상태에서 어떤 프로세스가 임계 구역에 진입하기를 원한다면 해당 프로세스를 임계 구역에 들어가게 해주어야 한다는 진행의 원리입니다. 마지막으로 Bounded Waiting은 유한 대기 즉, 어떤 프로세스가 임계 구역에 진입하기를 요청한 이후부터 그 요청이 허용될 때까지 다른 프로세스들이 임계 구역에 진입하는 횟수에 한계가 있어야 하며 진입하고자 하는 프로세스가 기아 현상을 경험해서는 안된다는 원리입니다.
