### ISSUE TITLE
🤔 [CH06]Q4 Spin lock은 어떠한 상황에서 발생하는지 설명해주세요.

### ISSUE THREAD

**Issue by dianestar** [CS-Oh-Yeahs/os_study#53]

**Comment by dianestar** [comment]
Busy Waiting이라고도 불리는 Spin Lock은 다른 스레드나 프로세스가 lock을 획득하고 Critical Section에 들어가 있어서 Critical Section에 진입이 불가능한 경우 진입이 가능해질 때까지 루프문을 돌며 진입 시도를 계속하는 방식으로 CPU time을 낭비하게 되는 문제를 갖습니다.

**Comment by gzgzg2** [comment]
Spin Lock은 한 프로세스가 임계구역에 접근한 상황에서 다른 프로세스가 CPU를 할당받고 임계구역에 접근을 시도할 경우 임계구역에 접근할 때 까지 while을 반복하여 CPU time을 낭비하는 문제를 말합니다.

**Comment by codenamehee** [comment]
Spin lock은 어떤 프로세스가 임계구역에 접근하고자 할 때, 이미 해당 임계구역을 획득하고 있던 프로세스가 있는 상황에서 발생하게 됩니다. 구체적으로는 어떤 프로세스가 자신의 CPU할당 시간동안 특정 임계구역에 진입하고자 할 때, 진입이 가능해지는 조건문의 조건을 만족하는지 체크하기 위해 계속해서 CPU와 메모리를 쓰면서 기다리게 되는 현상을 말합니다.
