### ISSUE TITLE
🤔 [CH06]Q5 Deadlock 과 Stavation의 차이를 설명해주세요.

### ISSUE THREAD

**Issue by dianestar** [CS-Oh-Yeahs/os_study#54]

**Comment by dianestar** [comment]
Deadlock이란 둘 이상의 프로세스가 서로에 의해 충족될 수 있는, 절대 일어나지 않을 이벤트나 자원 할당을 위해 무한히 대기하며 다음 처리를 진행하지 못하게 되는 상황을 말합니다. Starvation이란 다른 프로세스들끼리만 자원이나 프로세서를 할당 받으며 특정 프로세스가 자원 또는 프로세서를 할당 받지 못하고 무한히 기다리는 상황을 말합니다.

**Comment by gzgzg2** [comment]
Deadlock은 둘 이상의 프로세스가 서로 필요한 자원을 양보하지 않고 자원이 충족될 때까지 자원과 연관되어있는 프로세스들이 무한히 대기하는 현상을 말합니다.
Stavation은 다른 프로세스가 자원을 계속 가로채어 한 프로세스가 자원을 영원히 대기하게 되는 현상을 말합니다.

**Comment by codenamehee** [comment]
데드락은 서로 다른 프로세스들이 자원을 양보받기만을 무한히 기다리게 되는 현상을 말하고 Starvation은 기아현상으로 특정 프로세스들끼리만 자원을 공유하고, 어떤 프로세스는 자원을 획득하지 못하고 계속해서 기다리게 되는 현상을 말한다. 데드락은 자원과 연관되어 있는 모든 프로세스들이 무한히 대기하게 되므로 다음 작업이 진행되지 않지만 기아현상은 자원과 연관되어 있는 특정 프로세스들에 의해 작업은 계속해서 진행되는 상황에서 발생한다는 점에서 차이가 있다.
