### ISSUE TITLE
 🤔 [CH06]Q6 프로세스 동기화 문제가 발생하는 이유를 프로세스가 데이터에 접근하는 방식과 연관지어 설명해주세요.

### ISSUE THREAD

**Issue by dianestar** [CS-Oh-Yeahs/os_study#55]

**Comment by dianestar** [comment]
프로세스는 먼저 i) 메모리와 같은 데이터 저장소에서 데이터를 읽어오고 ii) 연산을 수행한 뒤 iii) 다시 데이터 저장소에 연산 결과를 저장하는 방식으로 데이터에 접근하게 됩니다. 프로세스가 각각의 독자적인 데이터 저장소만을 활용한다면 문제가 되지 않겠지만, 공유 데이터 저장소에 있는 데이터에 대해 이와 같은 과정을 수행할 경우 다수의 프로세스가 동일한 데이터에 접근하여 연산을 수행하고자 할 수 있기에 데이터 간 불일치 문제가 발생할 수 있습니다.

**Comment by gzgzg2** [comment]
프로세스는 데이터 저장소에서 필요한 데이터를 읽어와서 레지스터에 저장합니다. 해당 데이터로 연산이 끝날 때 레지스터에 있는 데이터를 메모리로 옮겨 적는데, 만약 이 데이터가 공유 데이터 저장소에서 사용하는 데이터일 경우 문제가 발생합니다. 
한 프로세스가 연산이 끝나기전에 time slice를 당하여 레지스터에 있는 데이터를 메모리로 옮기지 못했을 경우, 다른 프로세스가 동일한 공유데이터를 연산하여 반납하면 예상하지 못한 결과가 나올 수 있기 때문입니다.

**Comment by codenamehee** [comment]
데이터는 데이터를 저장하여 보관하는 위치와 연산이 수행되는 위치가 다르고 데이터의 갱신은 저장되어 있는 데이터를 꺼내어 연산을 수행한 후에 그 결과를 다시 원래 위치에 저장하는 식으로 진행된다. 이 과정에서 여러 프로세스들이 공유 데이터에 동시에 접근하여 연산을 수행하게 될 경우 프로세스들이 접하는 데이터들이 불일치되는 현상인 프로세스 동기화 문제가 발생할 수 있다.
