### ISSUE TITLE
🤔 [CH06]Q7 피터슨의 알고리즘에 대해 아는대로 설명해주세요.

### ISSUE THREAD

**Issue by dianestar** [CS-Oh-Yeahs/os_study#56]

**Comment by dianestar** [comment]
피터슨 알고리즘은 먼저 특정 프로세스 i가 critical section에 진입하고자 하는지 표시한 후 일단은 critical section 진입 순서를 다른 프로세스에게 양보한 후 critical section에 진입하고자 요청한 여타 프로세스가 없을 경우 프로세스 i가 critical section에 진입하게 되는 방식으로 Mutual Exclusion, Progress, Bounded Waiting을 모두 만족하는 알고리즘이라고 할 수 있습니다. 다만, 루프문을 돌며 busy waiting을 하며 CPU 시간을 낭비하게 되는 한 가지 문제점이 존재합니다.

**Comment by gzgzg2** [comment]
피터슨 알고리즘은 프로세스가 임계구역에 진입하기전에 자기자신의 접근의사를 true로 변경하고 다른 프로세스가 임계구역에 접근할 차례인지와 다른 프로세스의 임계구역 접근여부를 확인하고 모든 조건이 충족될 경우에 임계구역에 진입하는 알고리즘이다.
피터슨의 알고리즘은 다른 프로세스의 접근 차례와 접근 여부를 모두 검사하고 접근을 시도하기 때문에 프로세스 동기화 해결법의 충족 조건을 모두 만족한다.

**Comment by codenamehee** [comment]
피터슨의 알고리즘은 차례를 의미하는 turn과 임계 구역을 수행하겠다는 flag 변수를 모두 사용하여 특정 프로세스가 임계 구역의 코드를 수행하겠다고 표시한 후, 우선 다른 프로세스에게 차례를 넘겨 만약 해당 프로세스가 그 프로세스의 순서에 임계 구역을 수행하겠다고 표현했을 경우 차례를 양보하고 그렇지 않을 경우 자신이 임계 구역에 진입하는 방식을 통해 임계 구역의 3가지 조건을 모두 충족하는 알고리즘이다. 그러나 차례를 양보할지 양보하지 않을지를 결정하는 조건을 만족하는지 체크하기 위해 계속해서 CPU와 메모리를 소비하며 기다리는 Busy Waiting(Spin Lock) 현상이 발생할 수 있다는 단점이 있다.
