### ISSUE TITLE
🤔 [CH06]Q1 식사하는 철학자들 문제에서 발생할 수 있는 데드락을 예방하기 위한 방법을 두 가지 이상 설명해주세요.

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#57]

**Comment by dianestar** [comment]
i) 젓가락이 5개가 주어졌다고 할 때, 철학자 5명이 아닌 4명만 앉히는 방법, ii) 양쪽에 놓인 두 개의 젓가락을 동시에 잡을 수 있는 경우에만 젓가락을 획득하도록 하는 방법, iii) 홀수 번째 자리에 앉은 철학자는 왼쪽 젓가락, 짝수 번째 자리에 앉은 철학자는 오른쪽 젓가락과 같이 비대칭적으로 젓가락을 잡게 하는 방법이 있습니다.

**Comment by gzgzg2** [comment]
젓가락(자원) 5개가 주어졌다고 가정하에 4명의 철학자만이 테이블에 동시에 앉을 수 있도록 하는 방법과 젓가락(자원)을 모두 획득할 수 있을 때에만 젓가락을 잡을 수 있게하는 방법이 있습니다.

**Comment by codenamehee** [comment]
첫번째, 두개의 젓가락을 모두 잡을 수 있는 상황에서만 젓가락을 잡을 수 있게 제한하거나 두번째, 나란히 앉아있는 철학자 중 한명이 둘 사이의 젓가락을 먼저 잡았을 경우, 그 철학자가 나머지 젓가락 한 쪽도 잡을 수 있게 제한하는 방법과 마지막으로 4명의 철학자만이 테이블에 동시에 앉을 수 있게 제한하는 방법이 있다.
