### ISSUE TITLE
🤔 [CH06]Q2 임계구역을 보호하기 위한 방법 중 모니터에 대해 설명해주세요.

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#58]

**Comment by dianestar** [comment]
모니터란 공유 데이터 및 공유 데이터에 접근하는 프로시저를 모니터 내부에 정의하고, 모니터에 대한 프로세스들의 동시 접근을 허용하지 않음으로써 임계구역을 보호하는 high-level synchronization construct입니다.

**Comment by gzgzg2** [comment]
모니터란 공유 자원을 모니터 내부에 정의하고 공유자원에 대한 동시 접근을 허용하지 않는 high-level synchronization construct입니다.
모니터의 공유자원과 프로시저는 한 프로세스만이 접근 가능하므로 lock/unlock 기법을 필요로하지 않습니다. 이러한 특징은 프로그래머의 책임을 줄여준다는 장점이 있습니다.

**Comment by codenamehee** [comment]
모니터는 세마포어의 문제점을 보완하여 하나의 프로세스만이 내부에 정의된 프로시져를 통해 공유 데이터에 접근할 수 있도록 설계된 high-level synchronization constructor이다.
