### ISSUE TITLE
🤔 [CH06]Q3 세마포어의 문제점을 설명해주세요.

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#59]

**Comment by gzgzg2** [comment]
세마포어는 프로그래머가 직접 wait, signal 연산을 사용하여 자원의 획득과 해제를 동기화 문제가 발생하지 않게 코딩해야하며, 이는 코딩하기 어렵다는 단점과 프로그래머의 책임이 높아진다는 단점이 있습니다. 추가적으로 세마포어는 정확성 입증이 어렵고, 프로세스간 자발적 협력이 필요하다는 문제점이 있습니다.

**Comment by codenamehee** [comment]
세마포어는 프로그래머의 실수로 인해 임계 구역의 조건에 위배되거나 데드락 현상이 발생하는 등 모든 시스템에 치명적인 영향을 미칠 수 있고, 문제가 생겼을 때 버그를 잡기가 어렵다는 문제점이 있다.
