### ISSUE TITLE
🤔 [CH06]Q4 세마포어와 모니터의 차이첨을 설명해주세요.

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#60]

**Comment by dianestar** [comment]
세마포어는 프로그래머가 직접 코딩을 통해 lock을 걸어주어야 하는 반면, 모니터는 모니터 자체에 대한 동시 접근을 허용하지 않기 때문에 lock을 따로 걸어줄 필요가 없다는 차이점이 있습니다.

**Comment by gzgzg2** [comment]
세마포어는 공유자원에 다수의 프로세스가 접근할 수 있는 반면에 모니터는 공유자원에 하나의 프로세스만 접근할 수 있습니다. 이러한 특징 때문에 세마포어와 달리 lock/unlock을 수행할 필요가 없어집니다.

**Comment by codenamehee** [comment]
세마포어는 프로그래머가 직접 P연산을 통해 공유 자원에 lock을 걸어주어야 하지만 모니터는 자체적으로 하나의 프로세스만이 접근할 수 있도록 설계되었기 때문에 lock을 걸어줄 필요가 없다는 차이점이 있다.
