### ISSUE TITLE
🤔 [CH06]Q5 프로세스 동기화와 관련된 고전적 문제 3가지에 대해 각각 간단히 설명해주세요.

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#61]

**Comment by dianestar** [comment]
첫 번째 Bounded Buffer Problem은 생산자-소비자 문제라고도 불리며, 이는 버퍼가 공유 버퍼라는 점에서 다수의 생산자가 동일한 버퍼에 데이터를 입력하고자 하거나 다수의 소비자가 동일한 버퍼에 있는 데이터를 꺼내가려고 할 때 문제가 발생할 수 있으며, 또한 버퍼가 유한 버퍼라는 점에서 소비자의 요청은 없고 버퍼가 full인 상태에서 생산자가 계속해서 데이터를 입력하고자 하거나 반대로 생산자의 입력은 없고 버퍼가 empty인 상태에서 소비자가 계속해서 데이터를 꺼내가고자 할 때 문제가 발생할 수 있습니다. 두 번째 Readers-Writers Problem은 읽기 작업만 수행하는 프로세스가 공유 자원에 접근 중일 때에는 쓰기 작업을 수행하는 프로세스의 접근을 막기 위한 lock은 필요하지만 추가적인 읽기 프로세스가 접근하고자 할 때에는 접근을 허용해주어야 한다는 관점으로, Readers가 Writers보다 우선순위를 갖게 되므로 Writers의 Starvation 문제가 발생할 수 있습니다. 마지막으로, Dining Philosophers Problem은 5명의 철학자가 원탁 테이블에 앉아있고 철학자들 사이에 젓가락이 하나씩 놓여있으며 각각의 철학자는 자신의 양쪽에 놓인 젓가락 두 개를 모두 집어야 식사가 가능하다고 가정할 때, 모든 철학자가 자신의 왼쪽에 있는 젓가락을 동시에 집을 경우 모든 철학자가 식사를 할 수 없게 되는 문제로, Deadlock이 발생하는 원인을 직관적으로 볼 수 있는 예시라고 할 수 있습니다.

**Comment by gzgzg2** [comment]
프로세스 동기화와 관련된 세가지 문제는 1. Bounded-Buffer Problem, 2. Readers and Writers Problem, 3. Dining-Philosophers Problem 가 있는데

첫번째 문제점인 Bounded-Buffer Problem은 생산자와 사용자의 비율이 맞지않아서 사용자나 생산자가 무한히 대기하거나, 공우데이터에 동시에 접근하여 데이터 통일성이 깨질 수 있는 문제점을 얘기합니다.

Readers and Writers Problem는 다수의 Reader Writer가 공용 데이터베이스에 접근하여 데이터 일관성을 해치는 문제점을 말합니다.

Dining-Philosophers Problem은 하나 이상의 프로세스가 공유데이터 중 서로에게 필요한 자원을 양보하지 않아서 Deadlock이 발생할 수 있는 문제를 말합니다.

**Comment by codenamehee** [comment]
프로세스 동기화와 관련된 문제에는 생산자-소비자 문제 / readers-writers 문제 / 식사하는 철학자 문제가 있다.
먼저 생산자-소비자 문제는 버퍼의 크기가 유한한 환경에서 모든 버퍼에 데이터가 채워져 있을 경우 생산자 입장에서 가용 자원이 부족하게 되고, 데이터가 모두 비워져 있을 경우 소비자 입장에서 가용 자원이 부족해지는 문제와 데이터를 생산하는 여러 개의 생산자들이 하나의 버퍼에 동시에 도착해서 동시에 데이터를 추가하게 될 경우 발생할 수 있는 동기화 문제를 말한다. 
Readers-Writers 문제는 데이터를 변경하는 작업을 진행하는 프로세스는 한번에 하나의 프로세스만이 공유 데이터에 접근할 수 있어야 하고, 단순히 데이터를 읽기만 하는 프로세스는 한번에 여러 개의 프로세스들이 공유 데이터에 접근할 수 있게 해야한다는 관점이다. 이를 구현하는 과정에서 writer 프로세스는 모든 reader 프로세스들이 데이터를 읽고 나갈 때까지 계속해서 기다려야하는 starvation 현상이 발생할 수 있게 된다.
마지막으로 식사하는 철학자 문제는 데드락 현상을 설명한 것이다. 원탁에 앉아있는 5명의 철학자가 밥을 먹기 위해 자신의 양쪽에 있는 젓가락을 모두 잡아야 할 때, 5명의 철학자가 모두 자신의 왼쪽 젓가락을 잡으면 어떤 철학자도 오른쪽 젓가락을 잡을 수 없게 되어 더 이상 프로세스가 진행되지 않는 데드락과 같은 현상이 발생할 수 있음을 시사한다.
