### ISSUE TITLE
🤔 [CH06]Q6 모니터에서 사용되는 condition 변수란 무엇이고 이 변수와 관련되어 사용할 수 있는 연산에는 어떤 것이 있나요?

### ISSUE THREAD

**Issue by gzgzg2** [CS-Oh-Yeahs/os_study#62]

**Comment by gzgzg2** [comment]
condition 변수란 값을 가지지않고 프로세스가 프로세스를 자신의 큐에서 대기시키거나 깨우는 역할을 합니다. condition 변수는 wait과 signal을 통해서만 접근할 수 있습니다.

**Comment by codenamehee** [comment]
모니터의 Condition 변수는 공유 데이터에 접근하기 위해 대기하는 프로세스들의 상태를 나타내는 변수로, wait과 signal 연산을 통해 공유 데이터에 접근하기 위해 대기 큐에서 기다리면서 잠들게 하거나, 잠들어있는 프로세스를 깨우는 작업을 수행한다.
